#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sw:
  path: /sw.js
  controller: Symfony\Bundle\FrameworkBundle\Controller\AbstractController::renderFile
  defaults:
      path: '%kernel.project_dir%/public/assets/js/sw.js'
      mime_type: 'application/javascript'

download_database:
    path: /download-database
    controller: App\Controller\Admin\DashboardController::downloadDatabase
clear_chat:
    path: /clear_chat
    controller: App\Controller\Admin\DashboardController::clearChat
reach_us:
    path: /reach_us
    controller: App\Controller\HomeController::contact
not_found:
    path: /{catchall}
    controller: App\Controller\ErrorController::showNotFound
    requirements:
        catchall: '.*'